"""initial

Revision ID: 52467b682805
Revises:
Create Date: 2026-04-22 19:14:58.068147

"""

from typing import Sequence, Union

import sqlalchemy as sa  # noqa
from alembic import op  # noqa

# revision identifiers, used by Alembic.
revision: str = "52467b682805"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
