name: Ruff
on:
  push:
    branch: [development]
  pull_request:
    branch: [main, development]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Lint and Format
        run: |
          uvx ruff check .
          uvx ruff format --check .